FORMAT: 1A

# Group Authenticate SOCIAL

## Register [/auth/api/register]
### Register [POST]
+ Response 200 (application/json)

[
    {
    "message": "user successfully registered",
    "users": [
        {
        "name": "John Doe",
        "email": "john@gmail.com",
        "phone": 0939748336,
        "block": ['1','2'],
        "updated_at": "2020-06-16T20:42:51.0000z",
        "created_at": "2020-06-16T20:42:51.0000z"
        }
    ]
    }
]

## Login [/auth/api/login]
### Login [POST]

You need to enter your email and password

+ Request 200 (application/json)

{
    "accecss_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTYxODM4NTc3NywiZXhwIjoxNjE4Mzg5Mzc3LCJuYmYiOjE2MTgzODU3NzcsImp0aSI6InhWZWRob01RSWVxdUJ2NUwiLCJzdWIiOjU1LCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.W7P-dwrVey6dEwvVflBMmDyySUgCdPEt_kljSecaYmc",
    "user": [
        "name" => "john Doe"",
        "email" => "john@gmail.com",
        "phone" => "031355454232"
        "updated_at": "2020-06-16T20:42:51.0000z",
        "created_at": "2020-06-16T20:42:51.0000z"
        ]
}

+ Response 422 (application/json)

{
    "error": "Unauthorized",
}
## refresh [/auth/api/refresh]
### refresh [POST]
+ Request 200 (application/json)

{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9hdXRoXC9yZWZyZXNoIiwiaWF0IjoxNjE4Mzg2MjU1LCJleHAiOjE2MTgzODk4ODYsIm5iZiI6MTYxODM4NjI4NiwianRpIjoicDNQM2t1N3QweDQwMjNSeCIsInN1YiI6NTUsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.1s-7ZoqP2Kvwfp39DTVs2TmRPiHPYG4muWHVUBzcVIM",
    "token_type": "bearer",
    "expires_in": 3600,
    "user": {
        "id": 55,
        "name": "duongtv",
        "email": "duongtv2712@gmail.com",
        "phone": null,
        "block": null,
        "token_reset_password": null,
        "token_reset_password_at": null,
        "created_at": "2021-04-14T07:36:03.000000Z",
        "updated_at": "2021-04-14T07:36:03.000000Z"
    }
}
## Login [/auth/api/user-profile]
### user-profile [GET]
+ response 200 (application/json)
{
    "id": 55,
    "name": "duongtv",
    "email": "duongtv2712@gmail.com",
    "phone": null,
    "block": null,
    "token_reset_password": "8ujYLgOWg97Svws8khD8TyYUYZP3A9Ak3aVYHhWpfzq0qXJwmkO04TuZu38ZS5F1XWb1ECk27CN3JbRN",
    "token_reset_password_at": "2021-04-14 15:08:07",
    "created_at": "2021-04-14T07:36:03.000000Z",
    "updated_at": "2021-04-14T08:08:07.000000Z"
}
## Logout [/auth/api/logout]
### logout [POST]
+ Response 200 (application/json)
    "User successfully signed out"
## reset password [/auth/api/reset-password-request]
### Reset password [POST]
+ response 200 (application/json)
    "Check your inbox, we have sent a link to reset email"
## Change password [/auth/api/change-password]
### Change password [POST]
+ response 200 (application/json)
    "change password success !"
## Check token reset password at [/check-token-reset-password-at/{token}]
### Check token reset password at [GET]
+ response 404 (application/json)
{
    "error": "change password every 5 minutes"
}
+ response 404 (application/json)
{
    "password change over time"
}

FORMAT: 1A

# Group User SOCIAL

## LIST USER BLOCK [/auth/api/user/list-user-block]
### List user block [GET]
+ Response 200 (application/json)

[
    {

    "data": [
            {
                "id": 5,
                "name": "Nick Gutkowski",
                "email": "von.greta@example.org",
                "phone": "(272) 979-0956",
                "created_at": "2021-04-12T04:02:05.000000Z",
                "updated_at": "2021-04-12T04:02:05.000000Z"
            },
            {
                "id": 6,
                "name": "Jerome Lesch",
                "email": "joannie.nitzsche@example.com",
                "phone": "+1-678-265-5737",
                "created_at": "2021-04-12T04:02:05.000000Z",
                "updated_at": "2021-04-12T04:02:05.000000Z"
            },
            {
                "id": 1,
                "name": "Meta Armstrong",
                "email": "gkulas@example.com",
                "phone": "+19306800711",
                "created_at": "2021-04-12T04:02:05.000000Z",
                "updated_at": "2021-04-12T04:02:05.000000Z"
            },
            {
                "id": 2,
                "name": "Christ Lueilwitz",
                "email": "unique82@example.org",
                "phone": "(585) 552-6264",
                "created_at": "2021-04-12T04:02:05.000000Z",
                "updated_at": "2021-04-12T04:02:05.000000Z"
            }
        ]
    }
]

## ADD USER BLOCK [/auth/api/user/add-user-block]
### Add user block [POST]

+ Request 200 (application/json)

{
    "add success"
}

+ Response 404 (application/json)

{
    "error": "user already exists"
}
## REMOVE USER BLOCK [/auth/api/user/remove-user-block]
### Remove user block [POST]

+ Request 200 (application/json)

{
    "remove success"
}

+ Response 404 (application/json)

{
    "error": "user not in the list"
}
## CHANGE INFORMATION [/auth/api/user/change-information]
### change information [POST]

+ Request 200 (application/json)

{
    "Change information success"
}

## SEARCH USER [/auth/api/user/search-user]
### change information [GET]

+ Request 200 (application/json)

{
    "data": [
            {
                "id": 3,
                "name": "Harry Vandervort",
                "email": "ella91@example.net",
                "phone": "680.477.6740",
                "created_at": "2021-04-12T04:02:05.000000Z",
                "updated_at": "2021-04-12T04:02:05.000000Z"
            },
            {
                "id": 4,
                "name": "Dr. Jeramy Hamill IV",
                "email": "dee51@example.org",
                "phone": "+1-305-624-2592",
                "created_at": "2021-04-12T04:02:05.000000Z",
                "updated_at": "2021-04-12T04:02:05.000000Z"
            },
            {
                "id": 10,
                "name": "Geovany Hansen",
                "email": "monserrate18@example.net",
                "phone": "223-692-1434",
                "created_at": "2021-04-12T04:02:05.000000Z",
                "updated_at": "2021-04-12T04:02:05.000000Z"
            },
            {
                "id": 14,
                "name": "Hal Fadel II",
                "email": "haag.logan@example.com",
                "phone": "734-689-9565",
                "created_at": "2021-04-12T04:02:05.000000Z",
                "updated_at": "2021-04-12T04:02:05.000000Z"
            },
            {
                "id": 32,
                "name": "Mohamed Weimann",
                "email": "ottilie.cummerata@example.org",
                "phone": "(863) 533-6935",
                "created_at": "2021-04-12T04:02:05.000000Z",
                "updated_at": "2021-04-12T04:02:05.000000Z"
            },
            {
                "id": 41,
                "name": "Mr. Giuseppe Harris III",
                "email": "mante.alexandro@example.org",
                "phone": "(341) 449-4142",
                "created_at": "2021-04-12T04:02:05.000000Z",
                "updated_at": "2021-04-12T04:02:05.000000Z"
            }
        ],
        "links": {
            "first": "http://127.0.0.1:8000/api/user/search-user?page=1",
            "last": "http://127.0.0.1:8000/api/user/search-user?page=1",
            "prev": null,
            "next": null
        },
        "meta": {
            "current_page": 1,
            "from": 1,
            "last_page": 1,
            "links": [
                {
                    "url": null,
                    "label": "&laquo; Previous",
                    "active": false
                },
                {
                    "url": "http://127.0.0.1:8000/api/user/search-user?page=1",
                    "label": "1",
                    "active": true
                },
                {
                    "url": null,
                    "label": "Next &raquo;",
                    "active": false
                }
            ],
            "path": "http://127.0.0.1:8000/api/user/search-user",
            "per_page": 8,
            "to": 6,
            "total": 6
        }
}


FORMAT: 1A

# Group POST SOCIAL

## LIST POST [/auth/api/post/list-post]
### List post[GET]
+ Response 200 (application/json)

[
    {

       "data": [
               {
                   "id": 62,
                   "content": "duong th",
                   "status": 1,
                   "created_by": 1,
                   "share_post_id": null,
                   "created_at": "2021-04-20T06:48:27.000000Z",
                   "updated_at": "2021-04-20T06:48:27.000000Z",
                   "count_user_count": 0,
                   "like_count": 0,
                   "file": [
                       {
                           "id": 26,
                           "name": "/images/16189013073gCPv.png",
                           "post_id": 62,
                           "created_at": "2021-04-20T06:48:27.000000Z",
                           "updated_at": "2021-04-20T06:48:27.000000Z",
                           "filePath": "http://localhost:8000/storage/images/16189013073gCPv.png"
                       },
                       {
                           "id": 27,
                           "name": "/images/1618901307RokSU.png",
                           "post_id": 62,
                           "created_at": "2021-04-20T06:48:27.000000Z",
                           "updated_at": "2021-04-20T06:48:27.000000Z",
                           "filePath": "http://localhost:8000/storage/images/1618901307RokSU.png"
                       }
                   ]
               }
           ],
           "links": {
               "first": "http://127.0.0.1:8000/api/post/list-post/1?page=1",
               "last": "http://127.0.0.1:8000/api/post/list-post/1?page=1",
               "prev": null,
               "next": null
           },
           "meta": {
               "current_page": 1,
               "from": 1,
               "last_page": 1,
               "links": [
                   {
                       "url": null,
                       "label": "&laquo; Previous",
                       "active": false
                   },
                   {
                       "url": "http://127.0.0.1:8000/api/post/list-post/1?page=1",
                       "label": "1",
                       "active": true
                   },
                   {
                       "url": null,
                       "label": "Next &raquo;",
                       "active": false
                   }
               ],
               "path": "http://127.0.0.1:8000/api/post/list-post/1",
               "per_page": 2,
               "to": 1,
               "total": 1
           }
        }
]
## LIST POST [/auth/api/post/list-post-friend]
### List post friend[GET]
+ Response 200 (application/json)

[
    {

   "data": [
           {
               "id": 62,
               "content": "duong th",
               "status": 1,
               "created_by": 1,
               "share_post_id": null,
               "created_at": "2021-04-20T06:48:27.000000Z",
               "updated_at": "2021-04-20T06:48:27.000000Z",
               "count_user_count": 0,
               "like_count": 0,
               "file": [
                   {
                       "id": 26,
                       "name": "/images/16189013073gCPv.png",
                       "post_id": 62,
                       "created_at": "2021-04-20T06:48:27.000000Z",
                       "updated_at": "2021-04-20T06:48:27.000000Z",
                       "filePath": "http://localhost:8000/storage/images/16189013073gCPv.png"
                   },
                   {
                       "id": 27,
                       "name": "/images/1618901307RokSU.png",
                       "post_id": 62,
                       "created_at": "2021-04-20T06:48:27.000000Z",
                       "updated_at": "2021-04-20T06:48:27.000000Z",
                       "filePath": "http://localhost:8000/storage/images/1618901307RokSU.png"
                   }
               ]
           }
       ],
       "links": {
           "first": "http://127.0.0.1:8000/api/post/list-post/1?page=1",
           "last": "http://127.0.0.1:8000/api/post/list-post/1?page=1",
           "prev": null,
           "next": null
       },
       "meta": {
           "current_page": 1,
           "from": 1,
           "last_page": 1,
           "links": [
               {
                   "url": null,
                   "label": "&laquo; Previous",
                   "active": false
               },
               {
                   "url": "http://127.0.0.1:8000/api/post/list-post/1?page=1",
                   "label": "1",
                   "active": true
               },
               {
                   "url": null,
                   "label": "Next &raquo;",
                   "active": false
               }
           ],
           "path": "http://127.0.0.1:8000/api/post/list-post/1",
           "per_page": 2,
           "to": 1,
           "total": 1
       }
    }
]

## ADD POST [/auth/api/post/add-post]
### Add post [POST]

+ Request 200 (application/json)

{
    "add post success"
}

## REMOVE POST [/auth/api/post/remove-post]
### Remove post block [POST]

+ Request 200 (application/json)

{
    "remove post success"
}

## DETAIL POST [/auth/api/post/detail-post/2]
### detail post [GET]

+ Request 200 (application/json)

{
    "data": {
            "id": 4,
            "content": "fdfsffdfgggg",
            "status": 1,
            "created_by": 57,
            "share_post_id": null,
            "created_at": null,
            "updated_at": null
        }
}

## UPDATE POST [/auth/api/post/update-post/2]
### update post [POST]

+ Request 200 (application/json)

{
    "update post success"
}
## REMOVE POST [/auth/api/post/remove-post/2]
### remove post [POST]

+ Request 200 (application/json)

{
    "remove post success"
}
## USER LIKE [/auth/api/post/user-like/2]
### user like [POST]

+ Request 200 (application/json)

{
   "data": [
           {
               "id": 4,
               "content": "test 12345",
               "status": 1,
               "created_by": 57,
               "share_post_id": null,
               "created_at": null,
               "updated_at": "2021-04-19T02:46:46.000000Z",
               "like": []
           }
       ]
}
## USER SHARE [/auth/api/post/user-share/2]
### user-share [POST]

+ Request 200 (application/json)

{
    "data": [
            {
                "id": 4,
                "content": "test 12345",
                "status": 1,
                "created_by": 57,
                "share_post_id": null,
                "created_at": null,
                "updated_at": "2021-04-19T02:46:46.000000Z",
                "count_user": []
            }
        ]
}
FORMAT: 1A

# Group FRIEND SOCIAL

## LIST FRIEND [/auth/api/friend/list-friend]
### List friend[GET]
+ Response 200 (application/json)

[
    {

    "data": [
            {
                "id": 57,
                "name": "duongtv",
                "email": "duongtv2712@gmail.com",
                "phone": null,
                "created_at": "2021-04-19T02:40:25.000000Z",
                "updated_at": "2021-04-19T02:40:25.000000Z",
                "users": [
                    {
                        "id": 19,
                        "from_id": 18,
                        "to_id": 57,
                        "status": 1,
                        "created_at": null,
                        "updated_at": null
                    }
                ]
            }
        ]
    }
]

## REQUEST FRIEND [/auth/api/friend/request-friend]
### Request friend [POST]

+ Request 200 (application/json)

{
    "data": [
            {
                "id": 57,
                "name": "duongtv",
                "email": "duongtv2712@gmail.com",
                "phone": null,
                "created_at": "2021-04-19T02:40:25.000000Z",
                "updated_at": "2021-04-19T02:40:25.000000Z",
                "users": [
                    {
                        "id": 23,
                        "from_id": 57,
                        "to_id": 1,
                        "status": 0,
                        "created_at": "2021-04-19T03:00:51.000000Z",
                        "updated_at": "2021-04-19T03:00:51.000000Z"
                    },
                    {
                        "id": 20,
                        "from_id": 2,
                        "to_id": 57,
                        "status": 0,
                        "created_at": null,
                        "updated_at": null
                    },
                    {
                        "id": 21,
                        "from_id": 54,
                        "to_id": 57,
                        "status": 0,
                        "created_at": null,
                        "updated_at": null
                    },
                    {
                        "id": 22,
                        "from_id": 3,
                        "to_id": 57,
                        "status": 0,
                        "created_at": null,
                        "updated_at": null
                    }
                ]
            }
        ]
}

## SEND REQUEST FRIEND [/auth/api/friend/send-request-friend]
### send request friend [POST]

+ Request 200 (application/json)

{
    "send request friend success"
}

## REMOVE FRIEND [/auth/api/friend/remove-friend/2]
### remove friend [POST]

+ Request 200 (application/json)

{
    "remove request friend success"
}

## ACCEPT FRIEND [/auth/api/friend/accept-friend/2]
### accept friend [POST]

+ Request 200 (application/json)

{
    "accept request success"
}
## REMOVE POST [/auth/api/friend/remove-post/2]
### remove post [POST]

+ Request 200 (application/json)

{
    "remove post success"
}

